# FAKE NEWS CLASSIFIER

## Source: https://www.kaggle.com/competitions/fake-news

In [54]:
import pandas as pd

In [55]:
df=pd.read_csv('train.csv')

In [56]:
df.head()

id                                              title              author  \
0   0  House Dem Aide: We Didn’t Even See Comey’s Let...       Darrell Lucus   
1   1  FLYNN: Hillary Clinton, Big Woman on Campus - ...     Daniel J. Flynn   
2   2                  Why the Truth Might Get You Fired  Consortiumnews.com   
3   3  15 Civilians Killed In Single US Airstrike Hav...     Jessica Purkiss   
4   4  Iranian woman jailed for fictional unpublished...      Howard Portnoy   

                                                text  label  
0  House Dem Aide: We Didn’t Even See Comey’s Let...      1  
1  Ever get the feeling your life circles the rou...      0  
2  Why the Truth Might Get You Fired October 29, ...      1  
3  Videos 15 Civilians Killed In Single US Airstr...      1  
4  Print \nAn Iranian woman has been sentenced to...      1

In [57]:
#Checking null values
df.isnull().sum()

id           0
title      558
author    1957
text        39
label        0
dtype: int64

In [58]:
#drop the nan values
df=df.dropna()

In [59]:
df.shape

(18285, 5)

In [60]:
#Getting independent features
X=df.drop('label',axis=1)

In [61]:
#output column
y=df['label']

In [62]:
X.shape

(18285, 4)

In [63]:
y.shape

(18285,)

In [64]:
import tensorflow as tf

In [65]:
print(tf.__version__)

2.16.1


In [66]:
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense

In [67]:
#Defining a vocabulary size
voc_size=10000

In [68]:
messages=X.copy()

In [69]:
messages['title'][1]

'FLYNN: Hillary Clinton, Big Woman on Campus - Breitbart'

In [70]:
messages.reset_index(inplace=True)

In [71]:
messages

index     id                                              title  \
0          0      0  House Dem Aide: We Didn’t Even See Comey’s Let...   
1          1      1  FLYNN: Hillary Clinton, Big Woman on Campus - ...   
2          2      2                  Why the Truth Might Get You Fired   
3          3      3  15 Civilians Killed In Single US Airstrike Hav...   
4          4      4  Iranian woman jailed for fictional unpublished...   
...      ...    ...                                                ...   
18280  20795  20795  Rapper T.I.: Trump a ’Poster Child For White S...   
18281  20796  20796  N.F.L. Playoffs: Schedule, Matchups and Odds -...   
18282  20797  20797  Macy’s Is Said to Receive Takeover Approach by...   
18283  20798  20798  NATO, Russia To Hold Parallel Exercises In Bal...   
18284  20799  20799                          What Keeps the F-35 Alive   

                                          author  \
0                                  Darrell Lucus   
1                                Daniel J. Flynn   
2                             Consortiumnews.com   
3                                Jessica Purkiss   
4                                 Howard Portnoy   
...                                          ...   
18280                              Jerome Hudson   
18281                           Benjamin Hoffman   
18282  Michael J. de la Merced and Rachel Abrams   
18283                                Alex Ansary   
18284                              David Swanson   

                                                    text  
0      House Dem Aide: We Didn’t Even See Comey’s Let...  
1      Ever get the feeling your life circles the rou...  
2      Why the Truth Might Get You Fired October 29, ...  
3      Videos 15 Civilians Killed In Single US Airstr...  
4      Print \nAn Iranian woman has been sentenced to...  
...                                                  ...  
18280  Rapper T. I. unloaded on black celebrities who...  
18281  When the Green Bay Packers lost to the Washing...  
18282  The Macy’s of today grew from the union of sev...  
18283  NATO, Russia To Hold Parallel Exercises In Bal...  
18284    David Swanson is an author, activist, journa...  

[18285 rows x 5 columns]

In [72]:
import nltk
import re
from nltk.corpus import stopwords

In [73]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/shrey_98/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [74]:
### Preprocessing
from nltk.stem.porter import PorterStemmer
ps=PorterStemmer()

corpus=[]
for i in range (0,len(messages)):
    review=re.sub('[^a-zA-Z]',' ',messages['title'][i])
    review=review.lower()
    review=review.split()

    review=[ps.stem(word) for word in review if not word in stopwords.words('english')]
    review=' '.join(review)
    corpus.append(review)

In [75]:
corpus

['hous dem aid even see comey letter jason chaffetz tweet',
 'flynn hillari clinton big woman campu breitbart',
 'truth might get fire',
 'civilian kill singl us airstrik identifi',
 'iranian woman jail fiction unpublish stori woman stone death adulteri',
 'jacki mason hollywood would love trump bomb north korea lack tran bathroom exclus video breitbart',
 'beno hamon win french socialist parti presidenti nomin new york time',
 'back channel plan ukrain russia courtesi trump associ new york time',
 'obama organ action partner soro link indivis disrupt trump agenda',
 'bbc comedi sketch real housew isi caus outrag',
 'russian research discov secret nazi militari base treasur hunter arctic photo',
 'us offici see link trump russia',
 'ye paid govern troll social media blog forum websit',
 'major leagu soccer argentin find home success new york time',
 'well fargo chief abruptli step new york time',
 'anonym donor pay million releas everyon arrest dakota access pipelin',
 'fbi close hilla

## ONE HOT REPRESENTATION

In [76]:
ohe=[one_hot(word,voc_size)for word in corpus]
ohe

[[301, 3598, 109, 5617, 4610, 7407, 936, 6636, 3592, 8290],
 [9867, 152, 5312, 318, 3587, 2536, 1584],
 [1364, 1340, 753, 8002],
 [8450, 4545, 7972, 4537, 4903, 3985],
 [4805, 3587, 7877, 5624, 1846, 3857, 3587, 1348, 4353, 6411],
 [8057,
  2568,
  5769,
  7539,
  7384,
  5960,
  8406,
  6032,
  3848,
  2630,
  3441,
  5150,
  6322,
  6514,
  1584],
 [5516, 9711, 4183, 8765, 3492, 5734, 1218, 1158, 8748, 7508, 1867],
 [3186, 7199, 7780, 6324, 8224, 9055, 5960, 7630, 8748, 7508, 1867],
 [829, 5170, 3891, 3116, 3296, 7754, 3401, 9163, 5960, 4152],
 [4843, 4285, 4233, 8020, 4890, 4549, 723, 9697],
 [2695, 7489, 6005, 7954, 3648, 3766, 1460, 6738, 4636, 7703, 4483],
 [4537, 500, 4610, 7754, 5960, 8224],
 [7640, 4485, 4397, 684, 8396, 2477, 9010, 4500, 9934],
 [2079, 7801, 6142, 5929, 9819, 3187, 3818, 8748, 7508, 1867],
 [8155, 6270, 1253, 9443, 3524, 8748, 7508, 1867],
 [5894, 1432, 6670, 6258, 8947, 4036, 5751, 4269, 1784, 4224],
 [2027, 9008, 152],
 [5658, 527, 9349, 374, 5960, 5662, 89

## FEATURE REPRESENTATION
This is done to make sure that every feature has the same length and for that we do padding

In [77]:
sentence_length=30
embedded_docs=pad_sequences(ohe,maxlen=sentence_length,padding='pre')
print(embedded_docs)

[[   0    0    0 ... 6636 3592 8290]
 [   0    0    0 ... 3587 2536 1584]
 [   0    0    0 ... 1340  753 8002]
 ...
 [   0    0    0 ... 8748 7508 1867]
 [   0    0    0 ... 6063  634 3854]
 [   0    0    0 ... 5981 2852 8821]]


In [78]:
#verifying feature representation
print(embedded_docs[16251])

[   0    0    0    0    0    0    0    0    0    0    0    0    0    0
    0    0    0    0    0    0    0    0 2375 2101 3487 7801 3600 9656
 8609 3574]


In [85]:
## Creating a model
embedding_vec_features=40
model=Sequential()
model.add(Embedding(voc_size,embedding_vec_features))
model.add(LSTM(100))
model.add(Dense(1,activation='sigmoid'))
model.build(input_shape=(None, sentence_length))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])


In [86]:
model.summary()

Model: "sequential_9"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_9 (Embedding)         │ (None, 30, 40)         │       400,000 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_9 (LSTM)                   │ (None, 100)            │        56,400 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_9 (Dense)                 │ (None, 1)              │           101 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 456,501 (1.74 MB)

 Trainable params: 456,501 (1.74 MB)

 Non-trainable params: 0 (0.00 B)

In [87]:
len(embedded_docs),y.shape

(18285, (18285,))

In [91]:
import numpy as np
X_final=np.array(embedded_docs)
y_final=np.array(y)

In [92]:
X_final.shape,y_final.shape

((18285, 30), (18285,))

In [93]:
#train-test split
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X_final,y_final,random_state=0, test_size=0.2)

In [94]:
model.fit(X_train,y_train,validation_data=(X_test,y_test),epochs=10,batch_size=64)
          

Epoch 1/10
229/229 ━━━━━━━━━━━━━━━━━━━━ 5s 20ms/step - accuracy: 0.7964 - loss: 0.4046 - val_accuracy: 0.9245 - val_loss: 0.1765
Epoch 2/10
229/229 ━━━━━━━━━━━━━━━━━━━━ 4s 19ms/step - accuracy: 0.9499 - loss: 0.1281 - val_accuracy: 0.9327 - val_loss: 0.1660
Epoch 3/10
229/229 ━━━━━━━━━━━━━━━━━━━━ 6s 24ms/step - accuracy: 0.9720 - loss: 0.0784 - val_accuracy: 0.9330 - val_loss: 0.1702
Epoch 4/10
229/229 ━━━━━━━━━━━━━━━━━━━━ 5s 21ms/step - accuracy: 0.9874 - loss: 0.0437 - val_accuracy: 0.9319 - val_loss: 0.1925
Epoch 5/10
229/229 ━━━━━━━━━━━━━━━━━━━━ 5s 22ms/step - accuracy: 0.9903 - loss: 0.0342 - val_accuracy: 0.9237 - val_loss: 0.2660
Epoch 6/10
229/229 ━━━━━━━━━━━━━━━━━━━━ 5s 21ms/step - accuracy: 0.9963 - loss: 0.0155 - val_accuracy: 0.9286 - val_loss: 0.2712
Epoch 7/10
229/229 ━━━━━━━━━━━━━━━━━━━━ 5s 20ms/step - accuracy: 0.9983 - loss: 0.0101 - val_accuracy: 0.9270 - val_loss: 0.3466
Epoch 8/10
229/229 ━━━━━━━━━━━━━━━━━━━━ 5s 20ms/step - accuracy: 0.9982 - loss: 0.0082 - val_accu

In [95]:
y_pred=model.predict(X_test)

115/115 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step


In [96]:
y_pred=np.where(y_pred > 0.5,1,0) ##AUC ROC Curve

In [98]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test,y_pred))

0.9234345091605141


In [99]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.94      0.92      0.93      2040
           1       0.90      0.93      0.91      1617

    accuracy                           0.92      3657
   macro avg       0.92      0.92      0.92      3657
weighted avg       0.92      0.92      0.92      3657

