In [152]:
import pandas as pd


In [153]:
#importing the dataset
messages=pd.read_csv('NLP/smsspamcollection.txt', sep='\t',names=["label","message"])

In [53]:
messages

label                                            message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...
...    ...                                                ...
5567  spam  This is the 2nd time we have tried 2 contact u...
5568   ham               Will ü b going to esplanade fr home?
5569   ham  Pity, * was in mood for that. So...any other s...
5570   ham  The guy did some bitching but I acted like i'd...
5571   ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [154]:
messages.shape

(5572, 2)

In [55]:
messages['message'].loc[220]

"Yeah you should. I think you can use your gt atm now to register. Not sure but if there's anyway i can help let me know. But when you do be sure you are ready."

In [155]:
#Data cleaning and preprocessing
import re
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/shrey_98/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [156]:
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
ps=PorterStemmer()

In [157]:
corpus=[]
for i in range(0,len(messages)):
    review=re.sub('[^a-zA-Z0-9]',' ',messages['message'][i])
    review=review.lower()
    review=review.split()
    review=[ps.stem(word) for word in review if not word in stopwords.words('english')]
    review=' '.join(review)
    corpus.append(review)
                     
    

In [59]:
corpus

['go jurong point crazi avail bugi n great world la e buffet cine got amor wat',
 'ok lar joke wif u oni',
 'free entri 2 wkli comp win fa cup final tkt 21st may 2005 text fa 87121 receiv entri question std txt rate c appli 08452810075over18',
 'u dun say earli hor u c alreadi say',
 'nah think goe usf live around though',
 'freemsg hey darl 3 week word back like fun still tb ok xxx std chg send 1 50 rcv',
 'even brother like speak treat like aid patent',
 'per request mell mell oru minnaminungint nurungu vettam set callertun caller press 9 copi friend callertun',
 'winner valu network custom select receivea 900 prize reward claim call 09061701461 claim code kl341 valid 12 hour',
 'mobil 11 month u r entitl updat latest colour mobil camera free call mobil updat co free 08002986030',
 'gonna home soon want talk stuff anymor tonight k cri enough today',
 'six chanc win cash 100 20 000 pound txt csh11 send 87575 cost 150p day 6day 16 tsandc appli repli hl 4 info',
 'urgent 1 week free mem

In [158]:
#Creating a Bag of Words Model
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(max_features=2500,binary=True,ngram_range=(2,2))
X=cv.fit_transform(corpus).toarray()

In [159]:
X.shape

(5572, 2500)

In [160]:
X[1]

array([0, 0, 0, ..., 0, 0, 0])

In [161]:
#Label Encoding for spam and ham
y=pd.get_dummies(messages['label'],dtype=int)
y=y.iloc[:,1].values


In [163]:
y

array([0, 0, 1, ..., 0, 0, 0])

In [164]:
#Train-test split
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.20,random_state=0)

In [165]:
X_train,y_train

(array([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]]),
 array([0, 0, 0, ..., 1, 0, 0]))

In [166]:
from sklearn.naive_bayes import MultinomialNB
spam_detect_model=MultinomialNB().fit(X_train,y_train)

In [167]:
#prediction
y_pred=spam_detect_model.predict(X_test)

In [168]:
from sklearn.metrics import accuracy_score,classification_report


In [169]:
score=accuracy_score(y_test,y_pred)
print(score)

0.9721973094170404


In [170]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.97      1.00      0.98       955
           1       1.00      0.81      0.89       160

    accuracy                           0.97      1115
   macro avg       0.98      0.90      0.94      1115
weighted avg       0.97      0.97      0.97      1115



In [171]:
#Now creating a TF-IDF model
from sklearn.feature_extraction.text import TfidfVectorizer
tf=TfidfVectorizer(max_features=2500,ngram_range=(1,2))
X=tf.fit_transform(corpus).toarray()


In [172]:
#train-testsplit
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.20,random_state=0)

In [173]:
X_train,y_train

(array([[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]]),
 array([0, 0, 0, ..., 1, 0, 0]))

In [174]:
from sklearn.naive_bayes import MultinomialNB
spam_detect_model1=MultinomialNB().fit(X_train,y_train)

In [175]:
y_pred=spam_detect_model1.predict(X_test)

In [176]:
print(accuracy_score(y_pred,y_test))

0.9811659192825112


In [177]:
print(classification_report(y_pred,y_test))

              precision    recall  f1-score   support

           0       1.00      0.98      0.99       976
           1       0.87      1.00      0.93       139

    accuracy                           0.98      1115
   macro avg       0.93      0.99      0.96      1115
weighted avg       0.98      0.98      0.98      1115



In [178]:
from sklearn.ensemble import RandomForestClassifier
cf=RandomForestClassifier()


In [179]:
cf.fit(X_train,y_train)

RandomForestClassifier()

In [180]:
y_pred=cf.predict(X_test)

In [181]:
print(accuracy_score(y_pred,y_test))

0.9838565022421525


In [102]:
print(classification_report(y_pred,y_test))

              precision    recall  f1-score   support

           0       1.00      0.98      0.99       972
           1       0.89      1.00      0.94       143

    accuracy                           0.98      1115
   macro avg       0.95      0.99      0.97      1115
weighted avg       0.99      0.98      0.99      1115



# Word-2Vec

In [182]:
!pip install gensim

In [183]:
from nltk.stem import WordNetLemmatizer
lemmatizer=WordNetLemmatizer()

In [184]:
corpus=[]
for i in range(0,len(messages)):
    review=re.sub('[^a-zA-Z0-9]',' ',messages['message'][i])
    review=review.lower()
    review=review.split()
    review=[lemmatizer.lemmatize(word) for word in review if not word in stopwords.words('english')]
    review=' '.join(review)
    corpus.append(review)

In [185]:
corpus[0]

'go jurong point crazy available bugis n great world la e buffet cine got amore wat'

In [186]:
from nltk import sent_tokenize
from gensim.utils import simple_preprocess

In [187]:
words=[]
for sent in corpus:
    sent_token=sent_tokenize(sent)
    for sent in sent_token:
        words.append(simple_preprocess(sent))

In [188]:
words

[['go',
  'jurong',
  'point',
  'crazy',
  'available',
  'bugis',
  'great',
  'world',
  'la',
  'buffet',
  'cine',
  'got',
  'amore',
  'wat'],
 ['ok', 'lar', 'joking', 'wif', 'oni'],
 ['free',
  'entry',
  'wkly',
  'comp',
  'win',
  'fa',
  'cup',
  'final',
  'tkts',
  'st',
  'may',
  'text',
  'fa',
  'receive',
  'entry',
  'question',
  'std',
  'txt',
  'rate',
  'apply',
  'over'],
 ['dun', 'say', 'early', 'hor', 'already', 'say'],
 ['nah', 'think', 'go', 'usf', 'life', 'around', 'though'],
 ['freemsg',
  'hey',
  'darling',
  'week',
  'word',
  'back',
  'like',
  'fun',
  'still',
  'tb',
  'ok',
  'xxx',
  'std',
  'chgs',
  'send',
  'rcv'],
 ['even', 'brother', 'like', 'speak', 'treat', 'like', 'aid', 'patent'],
 ['per',
  'request',
  'melle',
  'melle',
  'oru',
  'minnaminunginte',
  'nurungu',
  'vettam',
  'set',
  'callertune',
  'caller',
  'press',
  'copy',
  'friend',
  'callertune'],
 ['winner',
  'valued',
  'network',
  'customer',
  'selected',
  're

In [189]:
import gensim

In [190]:
model=gensim.models.Word2Vec(words,window=5,min_count=2)

In [191]:
model.wv.index_to_key

['call',
 'get',
 'ur',
 'gt',
 'go',
 'lt',
 'ok',
 'day',
 'free',
 'know',
 'come',
 'like',
 'good',
 'time',
 'got',
 'text',
 'love',
 'want',
 'send',
 'need',
 'one',
 'txt',
 'today',
 'going',
 'stop',
 'home',
 'lor',
 'sorry',
 'see',
 'still',
 'mobile',
 'take',
 'back',
 'da',
 'reply',
 'dont',
 'think',
 'tell',
 'week',
 'phone',
 'hi',
 'new',
 'later',
 'please',
 'pls',
 'co',
 'msg',
 'make',
 'dear',
 'night',
 'message',
 'well',
 'say',
 'min',
 'thing',
 'much',
 'great',
 'claim',
 'hope',
 'oh',
 'hey',
 'give',
 'number',
 'happy',
 'friend',
 'work',
 'wat',
 'way',
 'yes',
 'www',
 'let',
 'prize',
 'right',
 'tomorrow',
 'already',
 'ask',
 'said',
 'win',
 'amp',
 'life',
 'cash',
 'yeah',
 'im',
 'tone',
 'really',
 'babe',
 'meet',
 'find',
 'miss',
 'morning',
 'uk',
 'last',
 'service',
 'thanks',
 'care',
 'com',
 'would',
 'anything',
 'year',
 'also',
 'lol',
 'nokia',
 'every',
 'feel',
 'keep',
 'sure',
 'pick',
 'urgent',
 'contact',
 'sent',


In [192]:
model.corpus_count

5565

In [193]:
model.epochs

5

In [194]:
model.wv.similar_by_word('football')

[('mail', 0.9825238585472107),
 ('weekend', 0.9825078248977661),
 ('support', 0.9825078248977661),
 ('dat', 0.9823575019836426),
 ('st', 0.982287585735321),
 ('post', 0.9822214245796204),
 ('flower', 0.9821692109107971),
 ('await', 0.9821227788925171),
 ('oso', 0.9821040630340576),
 ('easy', 0.9820618033409119)]

In [195]:
model.wv.similar_by_word('money')

[('one', 0.9996657967567444),
 ('today', 0.9996638894081116),
 ('give', 0.9996479153633118),
 ('thing', 0.9996469616889954),
 ('get', 0.9996356964111328),
 ('got', 0.9996323585510254),
 ('like', 0.9996315240859985),
 ('time', 0.9996263980865479),
 ('back', 0.9996228814125061),
 ('know', 0.9996210336685181)]

In [196]:
import numpy as np

In [197]:
def avg_word2vec(doc):
    
    return np.mean([model.wv[word] for word in doc if word in model.wv.index_to_key],axis=0)

In [130]:
!pip install tqdm

In [198]:
from tqdm import tqdm

In [199]:
X=[]
for i in tqdm(range(len(words))):
    X.append(avg_word2vec(words[i]))

  0%|                                                  | 0/5565 [00:00<?, ?it/s]/opt/anaconda3/lib/python3.11/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/opt/anaconda3/lib/python3.11/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
100%|████████████████████████████████████| 5565/5565 [00:00<00:00, 14815.39it/s]


In [200]:
words

[['go',
  'jurong',
  'point',
  'crazy',
  'available',
  'bugis',
  'great',
  'world',
  'la',
  'buffet',
  'cine',
  'got',
  'amore',
  'wat'],
 ['ok', 'lar', 'joking', 'wif', 'oni'],
 ['free',
  'entry',
  'wkly',
  'comp',
  'win',
  'fa',
  'cup',
  'final',
  'tkts',
  'st',
  'may',
  'text',
  'fa',
  'receive',
  'entry',
  'question',
  'std',
  'txt',
  'rate',
  'apply',
  'over'],
 ['dun', 'say', 'early', 'hor', 'already', 'say'],
 ['nah', 'think', 'go', 'usf', 'life', 'around', 'though'],
 ['freemsg',
  'hey',
  'darling',
  'week',
  'word',
  'back',
  'like',
  'fun',
  'still',
  'tb',
  'ok',
  'xxx',
  'std',
  'chgs',
  'send',
  'rcv'],
 ['even', 'brother', 'like', 'speak', 'treat', 'like', 'aid', 'patent'],
 ['per',
  'request',
  'melle',
  'melle',
  'oru',
  'minnaminunginte',
  'nurungu',
  'vettam',
  'set',
  'callertune',
  'caller',
  'press',
  'copy',
  'friend',
  'callertune'],
 ['winner',
  'valued',
  'network',
  'customer',
  'selected',
  're

In [148]:
type(X)

list

In [150]:
X

[array([-1.13650940e-01,  2.80761003e-01,  6.85846955e-02, -9.15270951e-03,
         3.15269106e-04, -4.02099133e-01,  4.67135459e-02,  5.04267752e-01,
        -1.49269059e-01, -1.04950868e-01, -1.03530042e-01, -3.97224218e-01,
        -6.29688501e-02,  4.74465154e-02,  8.77726749e-02, -2.15289190e-01,
        -2.33975966e-02, -3.67840499e-01, -2.69558933e-02, -3.95460576e-01,
         1.58527389e-01,  7.24067986e-02,  1.17664807e-01, -9.82804075e-02,
        -1.68078125e-01,  7.32147368e-03, -2.50589043e-01, -2.68182755e-01,
        -2.34157071e-01,  8.33577812e-02,  2.84144431e-01,  3.96712385e-02,
         1.01318873e-01, -1.31088719e-01, -1.16360061e-01,  2.37926885e-01,
        -4.19480093e-02, -2.75638282e-01, -1.77129135e-01, -4.80894953e-01,
         2.73398980e-02, -2.92911708e-01, -1.49442749e-02,  4.69002500e-03,
         2.19787300e-01, -1.46858960e-01, -2.07142308e-01, -9.23585787e-04,
         1.07701652e-01,  1.36769727e-01,  9.95300412e-02, -2.38263264e-01,
        -6.3

In [202]:
words[1]


['ok', 'lar', 'joking', 'wif', 'oni']

In [203]:
X_new=np.array(X)

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (5565,) + inhomogeneous part.