In [1]:
!python --version

Python 3.10.12


In [2]:
!pip --version

pip 23.1.2 from /usr/local/lib/python3.10/dist-packages/pip (python 3.10)


In [4]:
pip install tensorflow-gpu

  Using cached tensorflow-gpu-2.12.0.tar.gz (2.6 kB)
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  Preparing metadata (setup.py) ... error
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.


In [5]:
!pip install --upgrade pip setuptools wheel


     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 MB 8.0 MB/s eta 0:00:00
  Using cached setuptools-69.2.0-py3-none-any.whl (821 kB)
  Attempting uninstall: setuptools
    Found existing installation: setuptools 67.7.2
    Uninstalling setuptools-67.7.2:
      Successfully uninstalled setuptools-67.7.2
  Attempting uninstall: pip
    Found existing installation: pip 23.1.2
    Uninstalling pip-23.1.2:
      Successfully uninstalled pip-23.1.2
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
ipython 7.34.0 requires jedi>=0.16, which is not installed.


In [1]:
pip --version

pip 24.0 from /usr/local/lib/python3.10/dist-packages/pip (python 3.10)


In [2]:
pip install tensorflow

In [3]:
import tensorflow as tf


In [6]:
print(tf.__version__)

2.15.0


In [4]:
tf.test.gpu_device_name()


'/device:GPU:0'

In [4]:
from tensorflow.keras.preprocessing.text import one_hot

In [8]:
### sentences
sent=[ 'the glass of milk',
     'the glass of juice',
     'the cup of tea',
     'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good']

In [9]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [6]:
### define a vocab_size
voc_size=500

# ONE HOT REPRESENTATION

In [16]:
onehot_repr=[one_hot(words,voc_size)for words in sent]
print(onehot_repr)

[[347, 94, 296, 19], [347, 94, 296, 173], [347, 278, 296, 8], [234, 314, 22, 302, 130], [234, 314, 22, 302, 411], [102, 347, 190, 296, 61], [59, 373, 54, 302]]


# WORD EMBEDDING REPRESENTATION

In [10]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences ##to ensure all the sentences are of same length(we do padding)
from tensorflow.keras.models import Sequential

In [11]:
import numpy as np

In [18]:
## pre padding(zeroes added before)
sent_length=8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[  0   0   0   0 347  94 296  19]
 [  0   0   0   0 347  94 296 173]
 [  0   0   0   0 347 278 296   8]
 [  0   0   0 234 314  22 302 130]
 [  0   0   0 234 314  22 302 411]
 [  0   0   0 102 347 190 296  61]
 [  0   0   0   0  59 373  54 302]]


In [22]:
#feature represenation dimensions(vector represention) depends on how large the dataset is, it represents each index as vector representation
dim=10

In [20]:
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

In [21]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             5000      
                                                                 
Total params: 5000 (19.53 KB)
Trainable params: 5000 (19.53 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [24]:
#This is how the first sentence is vector represented
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 114ms/step


array([[ 0.0383484 ,  0.02242787,  0.00215833, -0.02564207, -0.01184119,
         0.04181245,  0.04613335,  0.04229114, -0.00847093, -0.02311238],
       [ 0.0383484 ,  0.02242787,  0.00215833, -0.02564207, -0.01184119,
         0.04181245,  0.04613335,  0.04229114, -0.00847093, -0.02311238],
       [ 0.0383484 ,  0.02242787,  0.00215833, -0.02564207, -0.01184119,
         0.04181245,  0.04613335,  0.04229114, -0.00847093, -0.02311238],
       [ 0.0383484 ,  0.02242787,  0.00215833, -0.02564207, -0.01184119,
         0.04181245,  0.04613335,  0.04229114, -0.00847093, -0.02311238],
       [ 0.04834289,  0.04343935,  0.03196228,  0.03399533,  0.04723673,
        -0.02848938,  0.0190212 , -0.02155898,  0.01176723,  0.04387097],
       [ 0.02549181,  0.02513092, -0.01478939,  0.0371428 ,  0.03540986,
         0.03083385, -0.01969227, -0.01128118,  0.01568128, -0.02249426],
       [ 0.01487056, -0.02218933, -0.009503  , -0.02134066, -0.03849093,
         0.01663813,  0.01693671,  0.00229919

In [25]:
embedded_docs[0]

array([  0,   0,   0,   0, 347,  94, 296,  19], dtype=int32)

In [27]:
#For all the sentences
print(model.predict(embedded_docs))

1/1 [==============================] - 0s 39ms/step
[[[ 0.0383484   0.02242787  0.00215833 -0.02564207 -0.01184119
    0.04181245  0.04613335  0.04229114 -0.00847093 -0.02311238]
  [ 0.0383484   0.02242787  0.00215833 -0.02564207 -0.01184119
    0.04181245  0.04613335  0.04229114 -0.00847093 -0.02311238]
  [ 0.0383484   0.02242787  0.00215833 -0.02564207 -0.01184119
    0.04181245  0.04613335  0.04229114 -0.00847093 -0.02311238]
  [ 0.0383484   0.02242787  0.00215833 -0.02564207 -0.01184119
    0.04181245  0.04613335  0.04229114 -0.00847093 -0.02311238]
  [ 0.04834289  0.04343935  0.03196228  0.03399533  0.04723673
   -0.02848938  0.0190212  -0.02155898  0.01176723  0.04387097]
  [ 0.02549181  0.02513092 -0.01478939  0.0371428   0.03540986
    0.03083385 -0.01969227 -0.01128118  0.01568128 -0.02249426]
  [ 0.01487056 -0.02218933 -0.009503   -0.02134066 -0.03849093
    0.01663813  0.01693671  0.00229919 -0.04658703  0.00170166]
  [-0.00013166 -0.04484273 -0.01942237  0.03639833  0.04742

In [1]:
sentence=["The world is a better place",
      "Marvel series is my favourite movie",
      "I like DC movies",
      "Cat is eating the food",
      "Tom and Jerry is my favourite cartoon ",
      "Python is my favourite progamming language"]

# Now applying ONE HOT Encoding

In [9]:
ohe=[one_hot(words,voc_size)for words in sentence]
print(ohe)

[[238, 466, 129, 325, 384, 289], [199, 474, 129, 398, 365, 436], [359, 250, 171, 439], [48, 129, 273, 238, 237], [193, 386, 172, 129, 398, 365, 83], [251, 129, 398, 365, 214, 192]]


In [ ]:
dimensions=10

In [13]:
### Now applying word embedding
sentence_length=10
embed=pad_sequences(ohe,padding='pre',maxlen=sentence_length)
print(embed)

[[  0   0   0   0 238 466 129 325 384 289]
 [  0   0   0   0 199 474 129 398 365 436]
 [  0   0   0   0   0   0 359 250 171 439]
 [  0   0   0   0   0  48 129 273 238 237]
 [  0   0   0 193 386 172 129 398 365  83]
 [  0   0   0   0 251 129 398 365 214 192]]


In [14]:
### Now applying a sequential model

model1=Sequential()
model1.add(Embedding(voc_size,10,input_length=sentence_length))
model1.compile('adam','mse')

In [15]:
model1.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 10, 10)            5000      
                                                                 
Total params: 5000 (19.53 KB)
Trainable params: 5000 (19.53 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [17]:
model1.predict(embed)

1/1 [==============================] - 0s 34ms/step


array([[[ 1.30610578e-02,  3.57828252e-02, -2.64324192e-02,
         -2.53576525e-02, -1.57309547e-02,  4.28536274e-02,
         -7.72244856e-03,  4.32051085e-02,  8.59634951e-03,
          2.25448646e-02],
        [ 1.30610578e-02,  3.57828252e-02, -2.64324192e-02,
         -2.53576525e-02, -1.57309547e-02,  4.28536274e-02,
         -7.72244856e-03,  4.32051085e-02,  8.59634951e-03,
          2.25448646e-02],
        [ 1.30610578e-02,  3.57828252e-02, -2.64324192e-02,
         -2.53576525e-02, -1.57309547e-02,  4.28536274e-02,
         -7.72244856e-03,  4.32051085e-02,  8.59634951e-03,
          2.25448646e-02],
        [ 1.30610578e-02,  3.57828252e-02, -2.64324192e-02,
         -2.53576525e-02, -1.57309547e-02,  4.28536274e-02,
         -7.72244856e-03,  4.32051085e-02,  8.59634951e-03,
          2.25448646e-02],
        [-1.88020822e-02, -3.70453708e-02,  3.14284116e-04,
          5.24237007e-03,  6.40098006e-03,  4.62064892e-03,
          1.99435093e-02, -2.69940142e-02, -2.253404